### ISSUE TITLE
Try it out INT OpenFlow Experimenter Actions on AmLight testing env 

### ISSUE THREAD

**Issue by viniarck** [kytos-ng/noviflow#11]
This is for testing out all four INT OpenFlow Experimenter Actions, trying to push a flow for each of them on AmLight testing env with flow_manager

```
class NoviActionType(IntEnum):
    """Noviflow custom actions."""

    # Set BFD
    NOVI_ACTION_SET_BFD_DATA = 4

    # Push INT
    NOVI_ACTION_PUSH_INT = 12

    # Modify INT
    NOVI_ACTION_ADD_INT_METADATA = 13

    # Pop INT
    NOVI_ACTION_POP_INT = 14

    # Send INT report
    NOVI_ACTION_SEND_REPORT = 15
 ```
 
@ajoaoff  we'll need also to map the payloads to try to out accordingly, let me know if you have ideas or suggestions for this. @italovalcy @jab1982 let us know also which BFD parameter values are being planned to use in prod for the `NOVI_ACTION_SET_BFD_DATA`, trying to use similar values would be great.

**Comment by viniarck** [comment]
@italovalcy has recommend to check out `amlight/kytos_noviflow_bfd` and slightly adapt when trying this out. This is a pre-requisite before developing the INT NApp to make sure the experimenter actions and existing `noviflow` NApp works in practice (unit test on `noviflow` NApp is all set).

**Comment by italovalcy** [comment]
I've done some tests on the Noviflow Test Environment, and I was able to validate all 5 experimenter actions defined in kytos/noviflow Napp. During the tests I found some issues [1][2], but after fixing them, the tests were executed successfully. 

Here are some examples of the tests in the Noviflow switches:


1. Using the INT actions `push_int`, `pop_int`, and `add_int_metadata` `send_report`.

```
curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:11"}, "actions": [{"action_type": "push_int"}]}]}'
curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:12"}, "actions": [{"action_type": "pop_int"}]}]}'
curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:13"}, "actions": [{"action_type": "send_report"}]}]}'
curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:14"}, "actions": [{"action_type": "add_int_metadata"}]}]}'
```

2. Using the BFD Experimenter action

Create the BFD logical ports:
```
curl -X POST -H "Content-Type: application/json" -d '{"port_no": 2,"lport_no": 1002}' http://localhost:8181/api/italovalcy/grpc_noviflow/v1/create_bfd_logicalport/00:00:00:00:00:00:00:01
curl -X POST -H "Content-Type: application/json" -d '{"port_no": 2,"lport_no": 1002}' http://localhost:8181/api/italovalcy/grpc_noviflow/v1/create_bfd_logicalport/00:00:00:00:00:00:00:02
```

Start the BFD session:

```
curl -X POST -H "Content-Type: application/json" -d '{
           "dpid_a": "00:00:00:00:00:00:00:01",
           "dpid_z": "00:00:00:00:00:00:00:02",
           "portno_a": 1002,
           "portno_z": 1002,
           "my_disc_a": 1,
           "my_disc_z": 1,
           "interval": 100000,
           "multiplier": 3,
           "flags": 1,
           "eth_a": "00:00:00:00:00:01",
           "eth_z": "00:00:00:00:00:02",
           "ipv4_a": "10.0.0.1",
           "ipv4_z": "10.0.0.2"
        }' http://localhost:8181/api/italovalcy/noviflow_bfd/v1/start_session
``` 

It was tested the following scenarios:

- Creation of the flows (send the flows through flow_manager and check the switch to confirm the flows are correct)
- Persistency (create the flows and restart Kytos to check they are still there; also validated directly on mongo DB)
- Consistency (removed and changed the flows at the switch's flow table to make sure flow_manager will recreate them properly)

[1] https://github.com/kytos-ng/noviflow/issues/18
[2] https://github.com/kytos-ng/flow_manager/issues/117

@viniarck please let me know if you meant something else for this issue or if we can close it.

**Comment by viniarck** [comment]
> I've done some tests on the Noviflow Test Environment, and I was able to validate all 5 experimenter actions defined in kytos/noviflow Napp. During the tests I found some issues [1][2], but after fixing them, the tests were executed successfully.
> 
> Here are some examples of the tests in the Noviflow switches:
> 
> 1. Using the INT actions `push_int`, `pop_int`, and `add_int_metadata` `send_report`.
> 
> ```
> curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:11"}, "actions": [{"action_type": "push_int"}]}]}'
> curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:12"}, "actions": [{"action_type": "pop_int"}]}]}'
> curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:13"}, "actions": [{"action_type": "send_report"}]}]}'
> curl http://127.0.0.1:8181/api/kytos/flow_manager/v2/flows/00:00:00:00:00:00:00:0c -H Content-type: application/json -d '{"flows": [{"priority": 100, "match": {"in_port": 23, "dl_src": "11:22:33:44:55:14"}, "actions": [{"action_type": "add_int_metadata"}]}]}'
> ```
> 
> 2. Using the BFD Experimenter action
> 
> Create the BFD logical ports:
> 
> ```
> curl -X POST -H "Content-Type: application/json" -d '{"port_no": 2,"lport_no": 1002}' http://localhost:8181/api/italovalcy/grpc_noviflow/v1/create_bfd_logicalport/00:00:00:00:00:00:00:01
> curl -X POST -H "Content-Type: application/json" -d '{"port_no": 2,"lport_no": 1002}' http://localhost:8181/api/italovalcy/grpc_noviflow/v1/create_bfd_logicalport/00:00:00:00:00:00:00:02
> ```
> 
> Start the BFD session:
> 
> ```
> curl -X POST -H "Content-Type: application/json" -d '{
>            "dpid_a": "00:00:00:00:00:00:00:01",
>            "dpid_z": "00:00:00:00:00:00:00:02",
>            "portno_a": 1002,
>            "portno_z": 1002,
>            "my_disc_a": 1,
>            "my_disc_z": 1,
>            "interval": 100000,
>            "multiplier": 3,
>            "flags": 1,
>            "eth_a": "00:00:00:00:00:01",
>            "eth_z": "00:00:00:00:00:02",
>            "ipv4_a": "10.0.0.1",
>            "ipv4_z": "10.0.0.2"
>         }' http://localhost:8181/api/italovalcy/noviflow_bfd/v1/start_session
> ```
> 
> It was tested the following scenarios:
> 
> * Creation of the flows (send the flows through flow_manager and check the switch to confirm the flows are correct)
> * Persistency (create the flows and restart Kytos to check they are still there; also validated directly on mongo DB)
> * Consistency (removed and changed the flows at the switch's flow table to make sure flow_manager will recreate them properly)
> 
> [1] #18 [2] [kytos-ng/flow_manager#117](https://github.com/kytos-ng/flow_manager/issues/117)
> 
> @viniarck please let me know if you meant something else for this issue or if we can close it.

Excellent news, @italovalcy, fantastic milestone seeing this working in practice, yes, that was it. Feel free to close it. 

Thanks for the tests/patches.
